name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@1.4.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: ":octocat: **RSDT** ha hecho un push en **${{ github.repository }}**\nMensaje: ${{ github.event.head_commit.message }}\n🔗 ${{ github.event.head_commit.url }}"
