name: Discord Notification

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "@everyone 🐙 **Nuevo update en ${{ github.repository }}**
          
Autor: ${{ github.actor }}
Mensaje: ${{ github.event.head_commit.message }}

📦 Repo: https://github.com/${{ github.repository }}
